// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW81gsifBqcazt_EVKoWymT6kCa7UFLlo',
    appId: '1:37849319186:web:32ad5565900fd5995715cb',
    messagingSenderId: '37849319186',
    projectId: 'foodon-832b9',
    authDomain: 'foodon-832b9.firebaseapp.com',
    storageBucket: 'foodon-832b9.firebasestorage.app',
    measurementId: 'G-H0K8NYRHL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlx_HnfwbP-FlUwopQNwEf4pzt76VDlx8',
    appId: '1:37849319186:android:7b6d13367338d32f5715cb',
    messagingSenderId: '37849319186',
    projectId: 'foodon-832b9',
    storageBucket: 'foodon-832b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNiZbSqKQqsFmlJhF59LnmiaP1lo3c4Y',
    appId: '1:37849319186:ios:b1c1475300ddc6915715cb',
    messagingSenderId: '37849319186',
    projectId: 'foodon-832b9',
    storageBucket: 'foodon-832b9.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW81gsifBqcazt_EVKoWymT6kCa7UFLlo',
    appId: '1:37849319186:web:cc06391b27b490b55715cb',
    messagingSenderId: '37849319186',
    projectId: 'foodon-832b9',
    authDomain: 'foodon-832b9.firebaseapp.com',
    storageBucket: 'foodon-832b9.firebasestorage.app',
    measurementId: 'G-J2720V6MKE',
  );
}
